### ISSUE TITLE
PC support?

### ISSUE THREAD

**Issue by IPeluchito** [Tauseef-Hilal/whatsapp_clone#7]
Hi, is it possible that you could add support for PC and now that it will be possible to add contacts from other applications from the original WhatsApp only with a username and without a phone number also support for it? It would be great if your application could be connected to the original WhatsApp, either from a cell phone or a computer!

**Comment by Tauseef-Hilal** [comment]
Hi @IPeluchito 
Thank you for your interest in the app! I appreciate your suggestion for PC support and the ability to connect to original WhatsApp. While I can certainly consider adding PC support in the future, I regret to inform you that connecting directly to original WhatsApp isn't feasible due to various technical and policy constraints. However, I've noted your feedback for future updates. Currently, the project is on hold, but I'll keep your suggestions in mind if I resume work on it down the line. Thank you for reaching out!

**Comment by IPeluchito** [comment]
Thanks to you for the effort to create such a wonderful app, I currently use uTox to communicate from the PC to the cell phone but the app has been outdated for years... I hope the same thing doesn't happen with your app...
Blessings!!!

**Comment by budi-fdln** [comment]
hi bro can you chat me on whatapp 
I want to develop the application that you made and add various new features to the conversation and it's not yet available on WhatsApp, are you willing to contact me?

**Comment by Tauseef-Hilal** [comment]
> hi bro can you chat me on whatapp 
> 
> I want to develop the application that you made and add various new features to the conversation and it's not yet available on WhatsApp, are you willing to contact me? 

Sure, email me your WhatsApp number.
Email: tantary.tauseef.atwork@gmail.com

**Comment by budi-fdln** [comment]
i was sent you my whatsapp number
